# Generated by Django 4.0.4 on 2022-06-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetModel',
        ),
    ]
