# Generated by Django 4.0.4 on 2022-07-07 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0004_alter_tweetmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='bad',
        ),
        migrations.RemoveField(
            model_name='tweetmodel',
            name='bad_user_list',
        ),
        migrations.RemoveField(
            model_name='tweetmodel',
            name='good',
        ),
        migrations.RemoveField(
            model_name='tweetmodel',
            name='good_user_list',
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.tweetmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
